### ISSUE TITLE
Require Recycling Error Logs

### ISSUE THREAD

**Issue by therealgemjosh** [Flutterwave/flutterwave-react-native#19]
I keep getting this error message whenever i click on the payment button. It does work but still i get this error | warning logs on my screen. Pls any suggestion on a quick fix to this?

![Screenshot 2021-03-15 033416](https://user-images.githubusercontent.com/40360041/111140449-925e0080-853f-11eb-8fa0-2a8dd72fbf68.png)
![Screenshot 2021-03-15 033944](https://user-images.githubusercontent.com/40360041/111140942-26c86300-8540-11eb-877c-4271b8e22b8b.png)

**Comment by thecodecafe** [comment]
Hi @therealgemjosh, unfortunately, there's no way to keep this from happening because of the dependency on `fetch` and `abortcontroller-polyfill` this polyfill helps us abort fetch requests. They kind of reference one another that's why the warning, but this does not impact performance and is supported. However, if you still want to keep the error from showing, simply add `console.ignoredYellowBox = ['Require cycle: node_module\''];` to the top of your application, this will keep the warning from showing. If this solves your problem, please reply so I can close the issue.
Thanks.

**Comment by therealgemjosh** [comment]
I did add the code snippet above to my index.js but still the warning persist. this is really going to be bad in production base application IMO

**Comment by thecodecafe** [comment]
All right @therealgemjosh glad your issue is solved, will be closing this for now.
